# Generated by Django 4.0.5 on 2022-06-05 20:05

import App_Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=5000, verbose_name='Book Title')),
                ('writer', models.CharField(max_length=5000, verbose_name='Writer')),
                ('publisher', models.CharField(max_length=5000, verbose_name='Publisher')),
                ('quality', models.CharField(max_length=5000, verbose_name='Quality')),
                ('book_description', models.TextField(verbose_name='Book Description')),
                ('total_page', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('main_cover', models.ImageField(upload_to=App_Home.models.book_directory_path, verbose_name='Main Cover Image')),
                ('book_cover1', models.ImageField(blank=True, null=True, upload_to=App_Home.models.book_directory_path, verbose_name='Cover Image 1')),
                ('book_cover2', models.ImageField(blank=True, null=True, upload_to=App_Home.models.book_directory_path, verbose_name='Cover Image 2')),
                ('book_cover3', models.ImageField(blank=True, null=True, upload_to=App_Home.models.book_directory_path, verbose_name='Cover Image 3')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
